version: '2'
services:
  jenkins:
    user: root
    image: 'jenkinsci/blueocean:latest'
    networks:
      - jenkinsnet
    ports:
      - '${JENKINS_HTTP_PORT}:8080'
      - '${JENKINS_HTTPS_PORT}:8443'
    volumes:
      - 'jenkins_data:/var/jenkins_home'
      - '${CODE_FOLDER}:/home/code'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - 'JENKINS_OPTS=--httpPort=8080 --httpsPort=8443'
  sonar:
    image: sonarqube
    networks:
      - jenkinsnet
    ports:
      - '${SONAR_HTTP_PORT}:9000'
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

volumes:
  jenkins_data:
    driver: local
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:

networks:
  jenkinsnet:
    driver: bridge
